# PostgreSQL.
# Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: pran
  password: 0
  host: localhost

development:
  <<: *default
  database: blog
test:
  <<: *default
  database: blog
# The production environment configuration is set via the DATABASE_URL environment variable.
# On platforms like Heroku, this is done automatically.
# On other platforms, you can explicitly set it.
production:
  <<: *default
  database: my_app_name_production
  username: my_app_name
  password: <%= ENV["MY_APP_NAME_DATABASE_PASSWORD"] %>
